spring:
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
