spring:
    datasource:
        url: jdbc:h2:mem:sdw2023 # Banco de dados em memória (H2)
        username: sdw2023 # Padrão do H2
        password: "" # Sem senha para o H2 em memória
    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: create # Cria ou atualiza o schema do banco de dados com base nas entidades
        properties:
            hibernate:
                format-sql: true # Dialeto do H2 para o Hibernate
    h2:
        console:
            enabled: true # Ativa o console web do H2
            path: /h2-console # Caminho do console (acessível em localhost:8080/h2-console)
            settings:
                trace: false
                web-allow-others: false
